name: Format

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions: 
      contents: write  
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install
        
      - name: Run Prettier
        run: yarn format
        
      - name: Generate Supabase Types 
        run: yarn codegen
        
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: format code with prettier"
          branch: ${{ github.head_ref || github.ref_name }} 